version: "3.9"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && rails assets:precompile && bundle exec rails db:migrate && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - railsgems:/usr/local/bundle
    ports:
      - "80:3000"
volumes:
  railsgems: